type = "Diamond"
entrypoint = "diamond_mariokart.dweam_game:MarioKartGame"
repo_link = "https://github.com/Dere-Wah/AI-MarioKart64"
thumbnail_dir = "thumbnails"

# Game-specific metadata
[games.mk64]
title = "Mario Kart 64"
tags = ["Racing"]
description = "A Mario Kart 64 model, trained on Luigi's Raceway."

[games.mk64.buttons]
"â¬…ï¸ Left" = "Arrow Left"
"â¡ï¸ Right" = "Arrow Right"
"ğŸ„ Use Item" = "D"
"ğŸ”„ Restart" = "Enter"